# Generated by Django 5.0.1 on 2024-04-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_c_solicitud_cirugias_cirugias_calendariocirugia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cirugias',
            old_name='persona_id',
            new_name='Persona_id',
        ),
    ]
