# Generated by Django 5.0.1 on 2024-04-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_persona_id_cirugias_persona_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='horarios_quirofano',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('HoraInicio', models.TimeField()),
                ('HoraFin', models.TimeField()),
                ('Tipo', models.CharField(choices=[('Cirugía de corazón', 'Cirugia De Corazon'), ('Cirugía de rodilla', 'Cirugia De Rodilla'), ('Cirugía de cataratas', 'Cirugia De Cataratas'), ('Cirugía de apéndice', 'Cirugia De Apendice'), ('Cirugía de columna', 'Cirugia De Columna')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='CalendarioCirugia',
        ),
    ]
